# vagrant plugin install vagrant-disksize

Vagrant.configure("2") do |config|
    config.vm.box = "debian/buster64"
    config.vm.customize ['createhd', '--filename', 'pgdata.vdi', '--size', 20 * 1024]
    config.vm.customize ['createhd', '--filename', 'wal.vdi', '--size', 10 * 1024]

    config.vm.provider "virtualbox" do |v|
        v.memory = 16800
        v.cpus = 6
        v.name = "dbstone"
    end
        
    
    config.vm.network "private_network", ip: "192.168.56.33"
    config.vm.hostname = "dbstone.local"
end